<?php

namespace App\Models;

use Database\Factories\LanguageFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * @property int $id
 * @property string $code
 * @property string $name
 * @property string|null $native_name
 * @property bool $is_active
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
class Language extends Model
{
    /** @use HasFactory<LanguageFactory> */
    use HasFactory;

    /**
     * The source language. Its catalog (lang/en.json) is generated by the
     * reconcile script and guarded by TranslationCatalogTest — the language
     * manager must never write or delete it.
     */
    public const DEFAULT_CODE = 'en';

    /**
     * Locale-code shape shared with SetLocale middleware. Doubles as the
     * path-traversal guard: the code becomes the lang/{code}.json filename.
     */
    public const CODE_PATTERN = '/^[a-z]{2}([_-][A-Za-z]{2,4})?$/';

    protected $fillable = [
        'code',
        'name',
        'native_name',
        'is_active',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
        ];
    }

    public function isDefault(): bool
    {
        return $this->code === self::DEFAULT_CODE;
    }

    /**
     * @param  Builder<Language>  $query
     * @return Builder<Language>
     */
    public function scopeActive(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }
}
